spring:
  application:
    name: IDENTITY-SERVICE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.207:5432/mdm
    username: mdm
    password: mdm
  jpa:
    database: postgresql
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

server:
  port: 9898

logging:
  level:
    org.springframework.security: DEBUG