spring:
  application:
    name: BOOKS-APP
server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

client:
  baseurl: http://localhost:3000

logging:
  level:
    org.springframework.security: DEBUG